### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by sachingiter** [Romanchuk/angular-i18next#57]
Great works for creating such a good module. It will be great if it supports IE11

**Comment by Romanchuk** [comment]
@sachingiter Hello, thanks. i18next supports ie11 and angular-i18next supports any browser depends on your project build config and polyfills setup.

Also, angular changed browser list support since v10. So read carefully migration steps you have to do:
“Version 10 of Angular Now Available” by Stephen Fluin https://link.medium.com/GJKUuMWbn8
